// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElLoadingDirective: typeof import('element-plus/es')['ElLoadingDirective']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
}
export {}
